CustomersProductsWebApp/Models/AddCustomerViewModel.cs
using DomainLayer.Models;
using System.ComponentModel.DataAnnotations.Schema;

namespace CustomersProductsWebApp.Models
{
    public class AddCustomerViewModel
    {
        public string Name { get; set; } = string.Empty;
        public string Address { get; set; } = string.Empty;
        public string PaymentType { get; set; } = string.Empty;
        public string Email { get; set; } = string.Empty;
        public long PhoneNumber { get; set; } = 0;
        public int PID { get; set; }
        //public ICollection<Product> Products { get; set; }
        [ForeignKey("PID")]
        public Product product { get; set; }
    }
}

CustomersProductsWebApp/Models/ErrorViewModel.cs
namespace CustomersProductsWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CustomersProductsWebApp/Models/UpdateCustomerViewModel.cs
using DomainLayer.Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace CustomersProductsWebApp.Models
{
	public class UpdateCustomerViewModel
	{
        [Key]
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Address { get; set; } = string.Empty;
        public string PaymentType { get; set; } = string.Empty;
        public string Email { get; set; } = string.Empty;
        public long PhoneNumber { get; set; } = 0;
        public int PID { get; set; }
        //public ICollection<Product> Products { get; set; }
        [ForeignKey("PID")]
        public Product product { get; set; }
    }
}

CustomersProductsWebApp/Controllers/CustomersController.cs
using System.Reflection.Metadata.Ecma335;
using CustomersProductsWebApp.Models;
using DomainLayer.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RepositoryLayer.DataAccessLayer;

namespace CustomersProductsWebApp.Controllers
{
    public class CustomersController : Controller
    {
        private readonly AppDbContext customerDbContext;

        public CustomersController(AppDbContext customerDbContext)
        {
            this.customerDbContext = customerDbContext;
        }

        public IActionResult Add()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {

            var customers = await customerDbContext.Customers.ToListAsync();
            return View(customers);

        }


        [HttpPost]
        public async Task<IActionResult> Add(AddCustomerViewModel addCustomerRequest)
        {
            var customer = new Customer()
            {
                Name = addCustomerRequest.Name,
                Email = addCustomerRequest.Email,
                PaymentType = addCustomerRequest.PaymentType,
                PhoneNumber = addCustomerRequest.PhoneNumber,
                Address = addCustomerRequest.Address,
                PID = addCustomerRequest.PID
            };

            await customerDbContext.Customers.AddAsync(customer);
            await customerDbContext.SaveChangesAsync();
            return RedirectToAction("Index");

        }
        [HttpGet]
        public async Task<IActionResult> View(int id)
        {
            var customer = await customerDbContext.Customers.FirstOrDefaultAsync(x => x.Id == id);

            if( customer != null)
            {
                var viewModel = new UpdateCustomerViewModel()
                {
                    Id = customer.Id,
                    Name = customer.Name,
                    Email = customer.Email,
                    PaymentType = customer.PaymentType,
                    PhoneNumber = customer.PhoneNumber,
                    Address = customer.Address,
                    PID = customer.PID
                };

                return await Task.Run(() => View("View",viewModel));

            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateCustomerViewModel model)
        {
            var customer = await customerDbContext.Customers.FindAsync(model.Id);

            if(customer != null)
            {
                customer.Name = model.Name;
                customer.Email = model.Email;
                customer.PaymentType = model.PaymentType;
                customer.PhoneNumber = model.PhoneNumber;
                customer.Address = model.Address;
                customer.PID = model.PID;

                await customerDbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateCustomerViewModel model)
        {
            var customer = await customerDbContext.Customers.FindAsync(model.Id);
            if(customer!= null)
            {
                customerDbContext.Customers.Remove(customer);
                await customerDbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

CustomersProductsWebApp/Controllers/HomeController.cs
using System.Diagnostics;
using CustomersProductsWebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace CustomersProductsWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CustomersProductsWebApp/Controllers/ProductsController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using RepositoryLayer.DataAccessLayer;
using DomainLayer.Models;
using Microsoft.EntityFrameworkCore;
using System.Xml.Linq;

namespace CustomersProductsWebApp.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class ProductsController : Controller
    {
        private readonly AppDbContext dbContext;

        public ProductsController(AppDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [HttpGet]
        public async Task<IActionResult> GetProducts()
        {
            return Ok(await dbContext.Products.ToListAsync());
            
        }

        [HttpPost]
        [Route("ADD")]
        public async Task<IActionResult> AddPerson(AddProduct _products)
        {
            var Products = new Product()
            {
                Name = _products.Name, 
                Description = _products.Description,
                Price = _products.Price
            };

            await dbContext.Products.AddAsync(Products);
            await dbContext.SaveChangesAsync();

            return Ok(Products);
        }

        //UPDATE DATA
        [HttpPut]
        [Route("Update/{Id:int}")]
        public async Task<IActionResult> UpdatePerson([FromRoute] int Id,UpdateProduct _products)
        {
            var Products = await dbContext.Products.FindAsync(Id);
            if (Products != null)
            {
                Products.Name = _products.Name;
                Products.Description = _products.Description;
                Products.Price = _products.Price;

                await dbContext.SaveChangesAsync();

                return Ok(Products);
            }

            return NotFound();
        }

        //DELETE DATA
        [HttpDelete]
        [Route("DELETE/{Id:int}")]
        public async Task<IActionResult> DeletePerson([FromRoute] int Id)
        {
            var Products = await dbContext.Products.FindAsync(Id);
            if (Products != null)
            {
                dbContext.Remove(Products);
                await dbContext.SaveChangesAsync();
                return Ok(Products);
            }
            return NotFound(nameof(Products));
        }
    }
}

CustomersProductsWebApp/Views/Customers/Add.cshtml
@model CustomersProductsWebApp.Models.AddCustomerViewModel;
@{
}
<h1>Add Customers:</h1>

<form method="post" action="Add" id="customerform">
    <div class="mb-3">
        <label for="exampleInputName" class="form-label">Full Name</label>
        <input type="text" class="form-control" id="InputName" asp-for ="Name">
    </div>
    <div class="mb-3">
        <label for="exampleInputEmail" class="form-label">Email</label>
        <input type="email" class="form-control" id="InputEmail" asp-for="Email">
    </div>
    <div class="mb-3">
        <label for="exampleInputAddress" class="form-label">Address</label>
        <input type="text" class="form-control" id="InputAddress" asp-for="Address">
       </div>
    <div class="mb-3">
        <label for="exampleInputPayment" class="form-label">Payment method</label>
        <input type="text" class="form-control" id="InputPayment" asp-for="PaymentType">
        </div>
    <div class="mb-3">
        <label for="exampleInputPhonenumber" class="form-label">Phone number</label>
            <input type="number" class="form-control" id="InputPhonenumber" asp-for="PhoneNumber">
    </div>
    <div class="mb-3">
        <label for="exampleInputPID" class="form-label">Product ID</label>
        <input type="number" class="form-control" id="InputPID" aria-describedby="pidHelp" asp-for="PID">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

CustomersProductsWebApp/Views/Customers/Index.cshtml
@model List<DomainLayer.Models.Customer>
@{
}

<h1> Customers</h1>

<table class="table">
	<thead>
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th>Email</th>
			<th>Address</th>
			<th>Phone number</th>
			<th>Payment type</th>
			<th>Product ID</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach(var customer in Model)
		{
			<tr>
				<td>@customer.Id</td>
				<td>@customer.Name</td>
				<td>@customer.Email</td>
				<td>@customer.Address</td>
				<td>@customer.PhoneNumber</td>
				<td>@customer.PaymentType</td>
				<td>@customer.PID</td>
				<td><a href="Customers/view/@customer.Id">View</a></td>
			</tr>
		}
	</tbody>
</table>

CustomersProductsWebApp/Views/Customers/View.cshtml
@model CustomersProductsWebApp.Models.UpdateCustomerViewModel;
@{
}
<h1>Update Customers</h1>
<form method="post" action="View" id="customerform">
    <div class="mb-3">
        <label for="exampleInputName" class="form-label">ID</label>
        <input type="text" class="form-control" id="InputName" asp-for="Id" readonly>
    </div>
    <div class="mb-3">
        <label for="exampleInputName" class="form-label">Full Name</label>
        <input type="text" class="form-control" id="InputName" asp-for ="Name">
    </div>
    <div class="mb-3">
        <label for="exampleInputEmail" class="form-label">Email</label>
        <input type="email" class="form-control" id="InputEmail" asp-for="Email">
    </div>
    <div class="mb-3">
        <label for="exampleInputAddress" class="form-label">Address</label>
        <input type="text" class="form-control" id="InputAddress" asp-for="Address">
       </div>
    <div class="mb-3">
        <label for="exampleInputPayment" class="form-label">Payment method</label>
        <input type="text" class="form-control" id="InputPayment" asp-for="PaymentType">
        </div>
    <div class="mb-3">
        <label for="exampleInputPhonenumber" class="form-label">Phone number</label>
            <input type="number" class="form-control" id="InputPhonenumber" asp-for="PhoneNumber">
    </div>
    <div class="mb-3">
        <label for="exampleInputPID" class="form-label">Product ID</label>
        <input type="number" class="form-control" id="InputPID" aria-describedby="pidHelp" asp-for="PID">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="submit" class="btn btn-danger"
                asp-action="Delete"
                asp-controller="Customers">Delete</button>
</form>

CustomersProductsWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CustomersProductsWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CustomersProductsWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CustomersProductsWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CustomersProductsWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Add">Add Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CustomersProductsWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>